# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [2]:
a = pd.Series([100,200,300,400])

Print a, and data type

In [3]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.Series'>

Using indexing access the element 300 from the series a.

In [4]:
print(a[2])

300

What are the values of index for series a?

In [5]:
a.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [6]:
a = pd.Series([100,200,300,400], index = ['a','b','c','d'])

a = a.reindex(['c','a','b','d'])
a

c    300
a    100
b    200
d    400
dtype: int64

Access the value in the series with index 'd'

In [7]:
a.loc[['d']]

d    400
dtype: int64

Sort the values wrt to the index and print it

In [8]:
a.sort_index()

a    100
b    200
c    300
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [9]:
b = pd.Series([800,450,100], index=['e','f','g'])
b

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [10]:
a = pd.concat([a,b])
a

c    300
a    100
b    200
d    400
e    800
f    450
g    100
dtype: int64

In [11]:
#print a again after appending b into it
a

c    300
a    100
b    200
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [12]:
a = a.sort_values(ascending=False)
a

e    800
f    450
d    400
c    300
b    200
a    100
g    100
dtype: int64

In [13]:
a = a.sort_index()
a

a    100
b    200
c    300
d    400
e    800
f    450
g    100
dtype: int64

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [14]:
df = pd.DataFrame(a)

In [15]:
df

     0
a  100
b  200
c  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [16]:
df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [17]:
# yep its same as the series.
a

a    100
b    200
c    300
d    400
e    800
f    450
g    100
dtype: int64

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [18]:
df.head()

     0
a  100
b  200
c  300
d  400
e  800

In [19]:
df.sort_index().tail()

     0
c  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [20]:
df.columns=['points']
df

   points
a     100
b     200
c     300
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [21]:
#Create fruits array
fruits = ['orange','mango','apple']

In [22]:
#Create series fruits out of fruits array
fruits = pd.Series(np.random.choice(fruits, size = 7))
fruits

0    orange
1     mango
2     mango
3    orange
4    orange
5    orange
6     mango
dtype: str

Change the index of fruits to the index of dataframe df

In [23]:
fruits.index = df.index
fruits

a    orange
b     mango
c     mango
d    orange
e    orange
f    orange
g     mango
dtype: str

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [24]:
fruits = pd.DataFrame(fruits, columns = ['fruits'])

In [25]:
fruits

   fruits
a  orange
b   mango
c   mango
d  orange
e  orange
f  orange
g   mango

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [26]:
d1 = { "city" : ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'], "Temperature" : [15,22,20,26,-2]}
d1 = pd.DataFrame(d1)

Print(d1)

In [27]:

d1

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [28]:

d1.shape

(5, 2)

Set city = d1['city']

In [29]:
city = d1['city']

print city <br>
What is the type of city.

In [30]:

print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: str
<class 'pandas.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [31]:
d2 = {"city" : ['Bengalaru', 'Coimbatore', 'Srirangam', 'Pondicherry'], "Temperature" : [24,35,36,39]}
d2 = pd.DataFrame(d2)

print the shape of this dataframe

In [32]:
d2
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [54]:
d3 = pd.merge(d1,d2, on=['city', 'Temperature'], how='outer')

d3

          city  Temperature
0    Bengalaru           24
1   Chandigarh           15
2      Chennai           26
3   Coimbatore           35
4        Delhi           22
5       Kanpur           20
6       Manali           -2
7  Pondicherry           39
8    Srirangam           36

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [55]:
d3[d3['Temperature'] <= 20]

         city  Temperature
1  Chandigarh           15
5      Kanpur           20
6      Manali           -2

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [56]:

d3[d3["Temperature"] >= 35]

          city  Temperature
3   Coimbatore           35
7  Pondicherry           39
8    Srirangam           36

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [57]:
# write function here

def is_ut(x):
    if x in ['Chandigarh', 'Pondicherry', 'Delhi']:
        return True
    else:
        return False

#     # write code below
d3['is_ut'] = d3['city'].apply(is_ut)

In [58]:
# print d3
d3

          city  Temperature  is_ut
0    Bengalaru           24  False
1   Chandigarh           15   True
2      Chennai           26  False
3   Coimbatore           35  False
4        Delhi           22   True
5       Kanpur           20  False
6       Manali           -2  False
7  Pondicherry           39   True
8    Srirangam           36  False

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [59]:
# write function here

def c_to_f(temp):
    temp = (temp*(9/5)) + 32
    return temp

In [60]:
# check function c_to_f(10)
temperature = int(input("Temperature"))
print(c_to_f(temperature))

Temperature 12

53.6

In [61]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)
d3

          city  Temperature  is_ut  temp_farenhiet
0    Bengalaru           24  False            75.2
1   Chandigarh           15   True            59.0
2      Chennai           26  False            78.8
3   Coimbatore           35  False            95.0
4        Delhi           22   True            71.6
5       Kanpur           20  False            68.0
6       Manali           -2  False            28.4
7  Pondicherry           39   True           102.2
8    Srirangam           36  False            96.8

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [52]:
d3[d3['is_ut'] == True],['city'],['is_ut']

(          city  Temperature  is_ut  temp_farenhiet
 1   Chandigarh           15   True            59.0
 4        Delhi           22   True            71.6
 7  Pondicherry           39   True           102.2,
 ['city'],
 ['is_ut'])

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [53]:

d3[d3['temp_farenhiet'] > 90],['city']

(          city  Temperature  is_ut  temp_farenhiet
 3   Coimbatore           35  False            95.0
 7  Pondicherry           39   True           102.2
 8    Srirangam           36  False            96.8,
 ['city'])

Select only the first three rows of the dataframe d1.

In [63]:
d3.head(3)

         city  Temperature  is_ut  temp_farenhiet
0   Bengalaru           24  False            75.2
1  Chandigarh           15   True            59.0
2     Chennai           26  False            78.8

Select all the rows and last two columns in the dataframe.

In [64]:
d3[['is_ut', 'temp_farenhiet']]

   is_ut  temp_farenhiet
0  False            75.2
1   True            59.0
2  False            78.8
3  False            95.0
4   True            71.6
5  False            68.0
6  False            28.4
7   True           102.2
8  False            96.8

## Groupby

In [69]:
# Create a dataframe using dictionary of your choice
data = { 'Name': ['Subhadeep', 'Soumili', 'Swarnita', 'Sutapa', 'Bhakta'],
          'Age': [23, 16, 21, 49, 57],
          'score': [70,80,90,100, 100],
          'dept' : ['IT', 'Arts', 'Laws', 'HR', 'HR']}
data = pd.DataFrame(data)
data

        Name  Age  score  dept
0  Subhadeep   23     70    IT
1    Soumili   16     80  Arts
2   Swarnita   21     90  Laws
3     Sutapa   49    100    HR
4     Bhakta   57    100    HR

In [70]:
# Use Groupby of single column with aggregate sum()
data.groupby('dept')['score'].sum()

dept
Arts     80
HR      200
IT       70
Laws     90
Name: score, dtype: int64

In [71]:
# Use Groupby of single column with aggregate count()
data.groupby('dept')['score'].count().loc[lambda x:x > 1]

dept
HR    2
Name: score, dtype: int64

In [74]:
# Use Groupby of single column with aggregate min() and max()
data.groupby('score').min()

            Name  Age  dept
score
70     Subhadeep   23    IT
80       Soumili   16  Arts
90      Swarnita   21  Laws
100       Bhakta   49    HR

In [75]:
data.groupby('dept')['Age'].max()

dept
Arts    16
HR      57
IT      23
Laws    21
Name: Age, dtype: int64

In [76]:
# Use Groupby of any 2 columns with aggregate mean()
data.groupby(['dept','Name'])['score'].mean()

dept  Name
Arts  Soumili       80.0
HR    Bhakta       100.0
      Sutapa       100.0
IT    Subhadeep     70.0
Laws  Swarnita      90.0
Name: score, dtype: float64

In [78]:
# Use Groupby of any 2 columns with aggregate min() and max()
data.groupby(['dept','Name'])['score'].agg(['min','max'])

                min  max
dept Name
Arts Soumili     80   80
HR   Bhakta     100  100
     Sutapa     100  100
IT   Subhadeep   70   70
Laws Swarnita    90   90